Feature/Add work rxjava
mercadolibre/mobile-dependencies_whitelist pull request #1002
Opened 2021-12-06 19:58 UTC by alexisrivs

# Todas las dependencias a proponer
- - "androidx.work:work-rxjava2:2.0.1"
- - "androidx.work:work-rxjava2:2.1.0"
...

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [x]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [x] _Tiene Min API level 14_

### Impacto en el peso de descarga e instalación de la app
- [x] _Work-RxJava Lib para la versión 2.1.0 ~4.0K._

# Libs externas
[x] [Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [TotpInApp PR](https://github.com/mercadolibre/fury_auth-security-two-fa-android/pull/60)

### Repositorios afectados
- [Security Two Fa](https://github.com/mercadolibre/fury_auth-security-two-fa-android)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2021-12-06 20:43 UTC, eduflores72 requested changes

2021-12-06 20:43 UTC, eduflores72 commented on android-whitelist.json
> +      "group": "androidx\\.work",
@alexisrivs para que necesitamos esta libs? del lado de arq estamos trabajando para eliminar rxjava 1 y 2, no podemos utilizar otra libs ??

2021-12-09 19:09 UTC, alexisrivs commented
@eduflores72 @abruno- 2022-03-24 ¿les parece como fecha de expiración?

2021-12-09 19:36 UTC, abruno- approved these changes

2021-12-09 19:50 UTC, eduflores72 approved these changes

2021-12-09 19:51 UTC, merged