Se agrega la app braze-android en el context y la whitelist de android
mercadolibre/mobile-dependencies_whitelist pull request #1015
Opened 2021-12-28 20:14 UTC by mlagonzalez

# Todas las dependencias a proponer
- - "com.mercadolibre.android.braze:braze:0.1.0"
- - "com.appboy:android-sdk-ui:15.0.0"

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [X]  _No, estas liberías no tienen código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _com.appboy:android-sdk-ui Tiene Min API level 16_
- [ ] _com.mercadolibre.android.braze:braze Tiene Min API level 21_

### Impacto en el peso de descarga e instalación de la app
- [X] _com.appboy:android-sdk-ui está pesando 603,7 KB_

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
N/D

### Repositorios afectados
- [mobile-notifications-android](https://github.com/mercadolibre/fury_mobile-notifications-android/)

## En qué apps impacta mi dependencia
- [X] Mercado Libre
- [X] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2021-12-29 13:55 UTC, abruno- commented
@mlagonzalez como va? podemos completar el form que figura en el template ? porque necesitamos esta lib ? el [context esta deprecado](git@github.com:mercadolibre/fury_auth-android-authentication.git)

2021-12-29 14:36 UTC, mlagonzalez commented
@abruno- Hola! Sí, el form de librerías externas lo estoy completando pero había unas cosas que estaba consultando con el equipo para poder terminarlo.

La librería se necesita porque estamos integrando Braze con las apps móviles para que los equipos de marketing puedan enviar notificaciones push con campañas promocionales.

Lo del context lo reviso y hago los cambios que se necesiten, gracias por el dato.

2022-01-03 15:44 UTC, mlagonzalez commented
Quité los cambiso del context y llené el formulario de liberías externas.

2022-01-07 21:17 UTC, snti approved these changes

2022-01-07 21:19 UTC, MathiasNunez approved these changes

2022-01-10 13:18 UTC, abruno- requested changes
Estamos revisando el form enviado, se enviaron comentarios q necesitan respuestas

2022-01-11 16:06 UTC, brgarelli approved these changes

2022-01-17 17:24 UTC, abruno- approved these changes

2022-01-17 17:24 UTC, merged