Tokenization dependency lib added
mercadolibre/mobile-dependencies_whitelist pull request #1025
Opened 2022-01-10 15:16 UTC by jorGonzalez291292

# Todas las dependencias a proponer
- com.mercadolibre.android.px.tokenization:core
- com.mercadolibre.android.px.tokenization:px-tokenization

### ¿Afecta al start-up time de alguna forma?
- _SI, mi Lib requiere inicialización en el `Application`_. Solo en Mercado libre. En Mercado Pago ya existe la inicialización.

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [x]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [x] _Tiene Min API level 23_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
Este proyecto usa internamente:
```
{
      "group": "com\\.mercadolibre\\.android\\.nfcpayments",
      "name": "hce-sdk",
      "version": "6\\.+"
    }
```

### Repositorios afectados
- [Card form](https://github.com/mercadolibre/card-form-android)
- [PX](https://github.com/mercadopago/px-android)
- [Wallet](https://github.com/mercadolibre/fury_mercadopago-android)
- [Marketplace](https://github.com/mercadolibre/fury_mercadolibre-android)

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-01-11 13:58 UTC, abruno- requested changes
@jorGonzalez291292 no tenemos min api 23 en las apps todavia.

2022-01-17 15:44 UTC, jorGonzalez291292 commented
@abruno- usamos ignite para revisar si podemos iniciar el flujo (en las reglas pedimos que el device sea api 23 por lo menos).

2022-01-17 17:20 UTC, abruno- commented
capaz q no entendi bien, pero la regla de min api 23 la ponen uds ? o es un requisito de la lib ?
Si no tenemos que modificar el minApi level de la app, estamos oka

2022-01-17 18:07 UTC, jorGonzalez291292 commented
@abruno- El SDK que usa la lib funciona con min api 23, por eso antes de iniciar el flujo usamos ignite para checkear que el device sea como mínimo api 23. No es necesario cambiar nada de la wallet o meli.

2022-01-17 18:34 UTC, abruno- commented
ok, te quedo con conflicts

2022-01-17 19:25 UTC, abruno- approved these changes

2022-01-19 18:14 UTC, eduflores72 approved these changes

2022-01-19 18:35 UTC, eduflores72 approved these changes

2022-01-19 19:39 UTC, eduflores72 approved these changes

2022-01-21 13:57 UTC, merged