Adding braze-ios and SDK to IOs whitelist
mercadolibre/mobile-dependencies_whitelist pull request #1026
Opened 2022-01-13 20:12 UTC by matiascaamano-meli

# Todas las dependencias a proponer
- "com.mercadolibre.ios.braze:braze:0.1.0"
- "com.appboy:android-sdk-ui:15.0.0"
...

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [x] AppBoySDK  está pesando 1MB._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-01-14 12:36 UTC, pigounet-meli approved these changes

2022-01-14 12:37 UTC, snti approved these changes

2022-01-14 12:56 UTC, pigounet-meli requested changes

2022-01-14 12:56 UTC, pigounet-meli commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre\\.android\\.braze",
Quedo con el formato de android, el nombre del pod deberia ser BrazeiOS (o el que diga el podspec de la llib que creamos)

2022-01-14 12:56 UTC, pigounet-meli commented on ios-whitelist.json
> +      "group": "com\\.appboy",
Acá debería ser el nombre del pod de iOS: Appboy-iOS-SDK/Core y Appboy-iOS-SDK/UI (validar por las dudas)

2022-01-17 17:25 UTC, caiomatosmeli approved these changes

2022-01-17 17:27 UTC, vmagnani approved these changes

2022-01-17 17:29 UTC, abruno- commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre",
@matiascaamano-meli podemos revisar esto ?
faltan las properties: source, target, y el nombre del grupo parece de android ?
idem nodo de abajo

2022-01-18 14:44 UTC, matiascaamano-meli commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre",
buenas!

debería ser algo así?

 {
      "name": "Braze-ios",
      "source": "private",
      "target": "production",
      "version": "1\\.0\\.0"
    },

2022-01-18 14:49 UTC, abruno- commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre",
revisemos la [documentacion](https://github.com/mercadolibre/mobile-dependencies_whitelist#ios)
cc @henrikemota

2022-01-19 18:40 UTC, matiascaamano-meli commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre",
lo actualicé siguiendo la documentacion

2022-01-25 21:05 UTC, matiascaamano-meli commented on ios-whitelist.json
> +      "group": "com\\.mercadolibre",
@abruno- ahora estaría correcto? gracias!!

2022-02-01 15:05 UTC, brgarelli requested changes
El nombre tiene que ser el mismo que figura [acá](https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-iOS-SDK.podspec), y la parte con el campo 'group' no va, solo el primer json object; la versión tiene que ir hasta 4.3.3 por compatibilidad, el regex quedaría algo así: "^~>4.3.[0-3]+$"

2022-02-01 16:32 UTC, matiascaamano-meli commented
> El nombre tiene que ser el mismo que figura [acá](https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-iOS-SDK.podspec) seguido por "/Core"- ya que de momento precisamos el código principal y no los demás subspecs-, y la parte con el campo 'group' no va, solo el primer json object; la versión tiene que ir hasta 4.3.3 por compatibilidad, el regex quedaría algo así: "^~>4.3.[0-3]+$"

gracias bruno!! ahi lo acomode, la version de Braze-ios esta bien poner la 1.0.0 o es mejor poner otra para que las posteriores versiones las tome tambien?

2022-02-04 12:37 UTC, pigounet-meli commented on ios-whitelist.json
> +      "version": "1\\.0\\.0"
```suggestion
      "version": "^~>\\s?1.[0-9]+"
```

2022-02-04 12:45 UTC, brgarelli approved these changes

2022-02-04 13:10 UTC, pigounet-meli approved these changes

2022-02-04 13:11 UTC, merged