Update MLAuthentication and MLLogin Modules
mercadolibre/mobile-dependencies_whitelist pull request #1029
Opened 2022-01-18 19:36 UTC by erasgido

# Todas las dependencias a proponer
Se actualizan las dependencias:
- MLLogin a 2.xx
- MLAuthentication a 1.xx

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [x] _Tiene Min iOS 12_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [MLLogin PR](https://github.com/mercadolibre/fury_auth-ios-login/pull/213)
- [MLLAuthentication PR](https://github.com/mercadolibre/fury_auth-ios-authentication/pull/32)

### Repositorios afectados
- [MLLogin](https://github.com/mercadolibre/fury_auth-ios-login)
- [MLAuthentication](https://github.com/mercadolibre/fury_auth-ios-authentication)

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [x] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-01-18 19:48 UTC, vmagnani approved these changes

2022-01-19 18:05 UTC, eduflores72 approved these changes

2022-01-19 19:39 UTC, eduflores72 approved these changes

2022-01-20 15:55 UTC, jsagredo-scott approved these changes

2022-01-20 17:16 UTC, fventre approved these changes

2022-01-21 14:26 UTC, eduflores72 requested changes
Estamos validando las fechas de expire con el team correspondiente, hasta mientras bloqueamos el PR

2022-01-21 14:58 UTC, erasgido commented
> Estamos validando las fechas de expire con el team correspondiente, hasta mientras bloqueamos el PR

Las fechas ya fueron charladas con @henrikemota 👍🏻

2022-04-06 20:38 UTC, eduflores72 commented
Se cierra este PR debido a que encontramos que este update podia generar afectación en otros equipos, se esta analizando que necesitamos para realizar el update.

2022-04-06 20:38 UTC, closed without merging