Matt android version update
mercadolibre/mobile-dependencies_whitelist pull request #1043
Opened 2022-02-01 16:00 UTC by scabrerameli

# Todas las dependencias a proponer
- "com.mercadolibre.android.matt:6.+"

### ¿Afecta al start-up time de alguna forma?
- No, mi Lib no requiere inicialización en el `Application`

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [X] No, MAtt-Android no tiene código con NDK

### Versiones mínimas y máximas del sistema operativo soportadas
- [X] La nueva versión tiene min API level 21

### Impacto en el peso de descarga e instalación de la app
- N/A

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [MAtt-Android PR #80](https://github.com/mercadolibre/fury_matt-android/pull/80)

### Repositorios afectados
- [ML Config Provider](https://github.com/scabrerameli/fury_ml-config-provider-android)
- [MP Config Provider](https://github.com/scabrerameli/fury_mp-config-provider-android)

## En qué apps impacta mi dependencia
- [X] Mercado Libre
- [X] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

2022-02-03 19:32 UTC, abruno- requested changes

2022-02-03 19:32 UTC, abruno- commented on android-whitelist.json
> +      "expires": "2022-05-15",
Siendo que las 2 versiones de la lib no pueden convivir en las apps, hay alguna razon para que pongamos el deadline casi terminando Q2?
Es complicado migrar a la version nueva de la lib ?

2022-02-04 12:25 UTC, scabrerameli commented on android-whitelist.json
> +      "expires": "2022-05-15",
Buenas! Pusimos esa fecha porque vamos a hacer a tomar el track en Q2 o quizás un poco antes. 
En ese caso, les parece mejor abrir el PR más cerca de la fecha?

2022-02-07 19:37 UTC, abruno- commented on android-whitelist.json
> +      "expires": "2022-05-15",
pasenlo cuando crean conveniente. Lo que necesitamos saber es si el cambio afecta a los equipos que todavia usan la 5.x y como se va a seguir esa migracion (si es que hace falta)

2022-02-11 12:35 UTC, closed without merging