updating androidx activity dependency
mercadolibre/mobile-dependencies_whitelist pull request #1073
Opened 2022-03-02 19:48 UTC by mordorq3git

# Description
Despues de la actualizacion de la version de kotlin, dejamos de usar las kotlin-android-extensions (ya que estan deprecadas), esto necesita que actualicemos las libs de las activities de androidx, para continuar con el soporte a viewModels

# Todas las dependencias a proponer
- "androidx.activity:activity:1.2.2" (java)
- "androidx.activity:activity-ktx:1.2.2" (kotlin)
...

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-03-02 20:28 UTC, abruno- requested changes

2022-03-02 20:32 UTC, mordorq3git commented on android-whitelist.json
> +      "version": "1\\.1\\.0|1\\.2\\.2"
@abruno- no se pueden mantener ambas? y que cada uno actualice on demand? (esto les va a pasar tarde o temprano a todos los q actualicen la version de kotlin y quieran remover las deprecated libs)

2022-03-02 20:38 UTC, abruno- commented on android-whitelist.json
> +      "version": "1\\.1\\.0|1\\.2\\.2"
no podemos mantener ambas, porque cuando se actualiza una lib en la app, se actualiza el stack para todas las libs, eso puede romper.

2022-03-03 13:06 UTC, mordorq3git commented on android-whitelist.json
> +      "version": "1\\.1\\.0|1\\.2\\.2"
claro, sisi, a eso lo entiendo @abruno- , pero nosotros somos una app aparte, entonces en estos casos si podrian convivir

2022-03-03 13:50 UTC, closed without merging

2022-03-03 15:11 UTC, abruno- commented on android-whitelist.json
> +      "version": "1\\.1\\.0|1\\.2\\.2"
ah, desde el contexto del PR no tenia esa info.
Igualmente queremos que el stack a nivel meli sea el mismo, y eso incluye o va a incluir el resto de las apps eventualmente. La buena noticia es que lo tenemos en radar y queremos actualizar proximamente