[expire] common  version
mercadolibre/mobile-dependencies_whitelist pull request #1075
Opened 2022-03-04 13:53 UTC by smattiauda-ml

# Todas las dependencias a proponer
- - "com.mercadolibre.android.commons:submodule:21.0.0"
...

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [x]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [x] _Tiene Min API level 21

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-03-04 17:48 UTC, abruno- requested changes

2022-03-04 17:48 UTC, abruno- commented on android-whitelist.json
> +      "expires": "2022-06-30",
@smattiauda-ml podemos poner el expire dentro de 4 semanas ? dado que en realidad no soportamos multiples versiones, no tiene sentido extender este expire

2022-03-07 14:56 UTC, abruno- approved these changes

2022-03-07 15:57 UTC, eduflores72 approved these changes

2022-03-07 15:58 UTC, merged