ajuste
mercadolibre/mobile-dependencies_whitelist pull request #1095
Opened 2022-03-28 16:30 UTC by gustavopolar

# Todas las dependencias a proponer
- - "com.somepackage.somelib:submodule:6.0.0"
...

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-03-28 19:24 UTC, eduflores72 commented on android-whitelist.json
> +    {
@gustavopolar porque necesitan esta version de melidata, siendo que ya tenemos la version 11.+ con expire y la version 12.+

2022-03-28 19:24 UTC, eduflores72 commented on android-whitelist.json
> +      "expires": "2022-04-28",
@gustavopolar este expire porque estarian necesitando actualizarlo con esa fecha?

2022-03-29 13:56 UTC, jiurchuk requested changes

2022-03-29 13:56 UTC, jiurchuk commented on android-whitelist.json
> +      "expires": "2022-04-28",
No es cuestión de extender el plazo sino de hacer el bump de la versión en la librería

2022-03-29 13:56 UTC, jiurchuk commented on android-whitelist.json
> +      "version": "1\\.\\+"
Elijamos una de las dos versiones.

2022-03-29 15:05 UTC, brgarelli approved these changes

2022-03-30 12:57 UTC, eduflores72 approved these changes

2022-03-30 21:09 UTC, caiomatosmeli approved these changes

2022-03-31 13:10 UTC, merged