Update activity-ktx version
mercadolibre/mobile-dependencies_whitelist pull request #1102
Opened 2022-03-31 00:12 UTC by iroman89

# Todas las dependencias a proponer
- "androidx.activity:activity-ktx:1.2.4"

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [x]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-03-31 17:04 UTC, eduflores72 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
@iroman89 porque necesitamos este update? porque solo se actualiza la version que soporta kotlin y no la que soporta java?

2022-03-31 17:23 UTC, iroman89 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
Se necesita para poder utilizar activityResultRegistry/ActivityResultContracts, olvidé actualizar la compatible con java, lo hago de una.

2022-03-31 17:30 UTC, iroman89 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
listo, actualizado

2022-04-04 13:29 UTC, eduflores72 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
@iroman89 estamos revisando si es que podemos actualizar esta libs, porque habian algunas libs que no podiamos actualizarlas..

2022-04-04 13:56 UTC, eduflores72 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
@iroman89 efectivamente como te comente recien, esta libs hoy no podemos actualizarla porque tiene varios blocker que estamos terminando de atacar para poder actualizarla.

2022-04-05 17:18 UTC, eduflores72 requested changes
esta libs hoy no podemos actualizarla porque tiene varios blocker que estamos terminando de atacar para poder actualizarla.

2022-04-06 14:09 UTC, iroman89 commented on android-whitelist.json
> -      "version": "1\\.1\\.0"
@eduflores72 no hay problema, lo cierro entonces, gracias.

2022-04-06 14:09 UTC, closed without merging