Se agrega la version de restart flow
mercadolibre/mobile-dependencies_whitelist pull request #1150
Opened 2022-04-27 19:02 UTC by matiasmanzanzani

# Todas las dependencias a proponer
- - "com.mercadolibre.inappupdates:in-app-updates:5.+"

### ¿Afecta al start-up time de alguna forma?
- _No, mi Lib no requiere inicialización en el `Application`_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-05-03 17:37 UTC, gussrivero approved these changes

2022-05-03 17:54 UTC, abruno- requested changes

2022-05-03 17:54 UTC, abruno- commented on android-whitelist.json
> +      "version": "4\\.\\+|5\\.\\+"
pongamos deadline a la version anterior

2022-05-30 13:17 UTC, abruno- approved these changes

2022-05-30 17:28 UTC, merged