Bump MLVPP major available
mercadolibre/mobile-dependencies_whitelist pull request #1161
Opened 2022-05-03 19:46 UTC by bqmeli

# Todas las dependencias a proponer
- Debido a los cambios de minimo de iOS, se sube la version del major para MLVPP en iOS a 2, por lo cual debemos soportar un major 2.0 en los podspec

### ¿Afecta al start-up time de alguna forma?
- No

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
- [ ]  _No, xxLib no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas
- [ ] _Tiene Min API level xx_

### Impacto en el peso de descarga e instalación de la app
- [ ] _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._

# Libs externas
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas)

### PRs abiertos con este Caso de uso
- [example PR](www.github.com/mercadolibre)

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2022-05-03 19:52 UTC, caiomatosmeli approved these changes

2022-05-03 19:57 UTC, vmagnani approved these changes

2022-05-03 20:27 UTC, eduflores72 requested changes

2022-05-03 20:27 UTC, eduflores72 commented on ios-whitelist.json
> +      "version": "^~>\\s?[0-2]+.[0-9]+"
@bqmeli consulta, la version 1.+ de la libs la utiliza algun equipo? porque en ese caso si mergeamos este PR podemos generarle conflictos a las personas que sigan utilizando la version antigua. te parece agregar un expire de la version de la libs?

2022-05-04 14:24 UTC, bqmeli commented on ios-whitelist.json
> +      "version": "^~>\\s?[0-2]+.[0-9]+"
Buenas @eduflores72 , la utiliza Homes, pero es un repo que estoy manteniendo yo, asi que no habría drama, que seria lo del expire ?

2022-05-04 20:50 UTC, bqmeli commented on ios-whitelist.json
> +      "version": "^~>\\s?[0-2]+.[0-9]+"
ahora si !

2022-05-04 20:53 UTC, eduflores72 approved these changes

2022-05-04 20:53 UTC, merged