Update Bugsnag Version
mercadolibre/mobile-dependencies_whitelist pull request #1282
Opened 2022-06-14 19:41 UTC by JohanD4

# Descripción
"com.bugsnag:bugsnag-android:5.22.4" (Se actualizó de la 5.15.0 a la 5.22.4)
"com.bugsnag:bugsnag-android-core:5.22.4" (Se actualizó de la 5.15.0 a la 5.22.4)
Se actualiza la version de Bugsnag de la 5.15.0 a la version 5.22.4 
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [X] Mercado Libre
- [X] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-06-16 13:11 UTC, abruno- commented on android-whitelist.json
>        "name": "bugsnag-android",
Eliminemos el nodo duplicado.
revisemos las otras libs que tambien son de bugsnag

2022-06-16 13:13 UTC, abruno- commented on android-whitelist.json
>        "name": "bugsnag-android-core",
idem

2022-06-16 14:09 UTC, abruno- requested changes
comments

2022-06-21 14:54 UTC, caiomatosmeli approved these changes

2022-06-21 15:09 UTC, abruno- commented on android-whitelist.json
> +      "version": "5\\.22\\.4"
ios no tiene version nueva?

2022-06-22 19:35 UTC, JohanD4 commented on android-whitelist.json
>        "name": "bugsnag-android",
Se agrega un expires a la version anterior de Bugsnag en la WhiteList

2022-06-22 19:35 UTC, JohanD4 commented on android-whitelist.json
>        "name": "bugsnag-android-core",
Se agrega un expires a la version anterior de Bugsnag en la WhiteList

2022-06-22 19:35 UTC, JohanD4 commented on android-whitelist.json
>        "name": "bugsnag-android",
Se agrega un expires a la version anterior de Bugsnag en la WhiteList.

La única lib que no se actualiza es 'bugsnag-plugin-android-okhttp' ya que esto es un plugin de bugsnag que se usa para los Breadcrumbs de networking por lo que no es necesario actualizarlo por ahora

2022-06-22 19:36 UTC, JohanD4 commented on android-whitelist.json
> +      "version": "5\\.22\\.4"
También se esta trabajando para actualizar Bugsnag en IOS, pronto se realizaran lo PR para esto

2022-06-27 13:16 UTC, merged