Bump Notif 21
mercadolibre/mobile-dependencies_whitelist pull request #1418
Opened 2022-09-15 17:41 UTC by manubla4

# Descripción
Bump Notif 21

Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-09-15 18:18 UTC, snti approved these changes

2022-09-16 00:12 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "3\\.\\+|4\\.\\+"
@manubla4 te parece agregar un expire para la version 3.+ ??

2022-09-16 00:12 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "20\\.\\+|21\\.\\+"
@manubla4 te parece agregar un expire para la version 20.+ ??

2022-09-16 00:15 UTC, eduflores72 requested changes
@manubla4 podemos validar los comments del PR, me hace ruido que tengamos mucho tiempo 4 versiones de una misma libs (com.mercadolibre.android.rich_notifications).

2022-09-19 20:34 UTC, eduflores72 approved these changes

2022-09-19 20:43 UTC, gussrivero commented on android-whitelist.json
> +      "expires": "2022-12-15",
@manubla4 deberiamos chequear estas fechas, entiendo que el cambio a Android 12 es bastante breaking change de parte de la lib de notificaciones. En ese caso debemos pushear el rapido cambio en las otras libs ya que las apps van a estar con la nueva version. Podria sugerir el deadline de api 32 30/09/2022

2022-09-19 21:08 UTC, manubla4 commented on android-whitelist.json
> +      "expires": "2022-12-15",
ahi lo arreglé @gussrivero

2022-09-19 21:14 UTC, merged