Gamification and Nfc bump
mercadolibre/mobile-dependencies_whitelist pull request #1436
Opened 2022-09-21 02:01 UTC by felixmeli

# Descripción
    
Se actualiza la versión de NFC y Gamification 

- com.mercadolibre.android.nfcpayments:core
- com.mercadolibre.android.nfcpayments:flows
- com.mercadolibre.android.gamification:gamification

La version 3.0.0 de NFC solo tendrá la migración a Android 12. A partir de la 4 tendremos los flavors mercadolibre y mercadopago. Por el momento solo el flavor de mercadopago será el que salga a producción. 

# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [X] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-09-21 13:02 UTC, eduflores72 requested changes

2022-09-21 13:02 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "mercadopago-4\\.\\+|\\3\\.+"
@felixmeli es necesario tener dos versiones activas? te parece dejar la ultima, y agregarle un expire a la 3.+? 
tambien checkeemos que \\3 es incorrecto, la forma correcta seria 3\\.+

2022-09-21 13:02 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "mercadopago-4\\.\\+|\\3\\.+"
idem comentario anterior

2022-09-27 15:53 UTC, felixmeli commented on android-whitelist.json
> +      "version": "mercadopago-4\\.\\+|\\3\\.+"
Estamos de acuerdo, mi idea era evitar dos pr pero tiene sentido que mantengamos una única versión productiva

2022-09-27 15:53 UTC, felixmeli commented on android-whitelist.json
> +      "version": "mercadopago-4\\.\\+|\\3\\.+"
idem

2022-09-27 15:54 UTC, felixmeli commented
Cierro el pr , cuando definamos una única versión productiva vuelvo a enviarlo. Gracias !

2022-09-27 15:54 UTC, closed without merging