[BUMP] Robolectric to 4.0.2 and 4.6.1 and deprectate old version (4.0.1 + 4.0.2)
mercadolibre/mobile-dependencies_whitelist pull request #1439
Opened 2022-09-21 17:32 UTC by lcarboneti

Agregamos robolectric 4.0.2 

Agregamos robolectric 4.6.1 : Soporte a java 11 para robolectric 

Necesitamos el cambio porque ci o local no va a poder correr robolectric con java 11 sin este bump

2022-09-21 20:58 UTC, eduflores72 approved these changes

2022-09-22 13:21 UTC, abruno- requested changes
en que repo falla el lint por estas libs?

2022-09-22 13:34 UTC, matiasmanzanzani commented
Robolectric 4.0.1 es la que usamos actualmente. Con AGP se necesita la Robolectric 4.6.1 para java 11 y luego hay un fix que se agrega en la v4.0.2 que es necesario para los PRs del Plugin de Gradle en donde se necesita ese bump y que no sea breaking change

2022-09-22 13:39 UTC, abruno- commented
Robolectric 4.6.1 no requiere java11, porque no vamos directamente por esa version ?¿

2022-09-22 14:15 UTC, lcarboneti commented
no bruno.. java 11 requiere robolectric > 4.5.1

2022-09-22 14:30 UTC, matiasmanzanzani commented
Te referis a en vez de ir a la 4.0.2 en el medio, usemos la 4.6.1 ?

El tema es que Edu me comento que es posible que haya que hacer correcciones en los test por detalles que cambian entre estas versiones, y me gustaría fixear el problema que tiene el Plugin de Gradle de la forma mas transparente y luego con la migración donde se sube a la 4.6.1 encargarse de esos detalles.

2022-09-22 14:32 UTC, lcarboneti commented
pueden probar si les falla con java 8 los pr y robolectrict 4.6.1?  en mis pruebas nunca me fallo

2022-09-22 14:55 UTC, matiasmanzanzani commented
Implementandolo en el mismo mobile testing ya genera conflictos, y el caso es que habria que probarlo en los 100 repos que ya estan migrados para verificar que la v 4.6.1 no rompe

https://gradle.adminml.com/s/vyznej6osjpug

2022-09-22 19:10 UTC, lcarboneti commented
estas compilando con java 11 mati no con 8

2022-09-22 20:10 UTC, lcarboneti commented
En las pruebas No se realizo la transitividad de la flag de jetifier :(

2022-09-22 20:13 UTC, lcarboneti commented
vamos por la 4.5.1 no falla

2022-09-26 13:22 UTC, abruno- approved these changes

2022-09-26 13:22 UTC, merged