Fix expiration date of totp
mercadolibre/mobile-dependencies_whitelist pull request #1454
Opened 2022-09-27 12:23 UTC by Priscila-A-Gomez

# Descripción
Deleted wrong date expiration of totp 6.+ version. 
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-09-27 12:24 UTC, gussrivero approved these changes

2022-10-11 18:03 UTC, lcarboneti requested changes
revisar comment

2022-10-13 13:23 UTC, lcarboneti commented on android-whitelist.json
> -      "expires": "2022-09-30",
@Priscila-A-Gomez  pudieron revisar esto?

2022-10-13 15:23 UTC, Priscila-A-Gomez commented on android-whitelist.json
> -      "expires": "2022-09-30",
Perdón por la demora en responder, se estaba eliminando el expire porque estaba repetido, no correspondía agregarlo en la versión 6.+. De todos modos, eso ya fue resuelto en el PR: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1520 , este PR puede ser desestimado.

2022-10-13 15:24 UTC, closed without merging