add new module mplay
mercadolibre/mobile-dependencies_whitelist pull request #1484
Opened 2022-10-03 21:50 UTC by julianlopezM

# Descripción
    ...
Se agrega la version de Mercado play 
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-10-04 13:31 UTC, eduflores72 commented on android-whitelist.json
> +      "expires": "2023-10-07",
@julianlopezM porque estamos agregando un expire a una version 1.+ y arriba estamos agregando la misma version ?

2022-10-11 18:02 UTC, lcarboneti requested changes
revisar comments

2022-11-22 13:32 UTC, eduflores72 commented
@julianlopezM podemos cerrar este PR? veo que esta hace mas de 20 dias.

2022-11-25 17:50 UTC, eduflores72 commented
se cierra el PR debido a que no se obtuvo respuesta y esta hace mas de 20 dias

2022-11-25 17:50 UTC, closed without merging