[SMARTY-6349] Add nav component to whitelist
mercadolibre/mobile-dependencies_whitelist pull request #1499
Opened 2022-10-06 18:39 UTC by geroillescas

# Descripción

Se agregan dependencias de navigation component para el desarrollo de funcionalidad de pago de servicios. Estas librerias estan limitadas hasta fin de Q2 donde se estima que ya haya un reemplazo por parte de meli para la navegacion de fragmentos.
# Ticket ID

[SMARTY-6349](https://mercadolibre.atlassian.net/browse/SMARTY-6349)

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [x] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-10-11 12:58 UTC, eduflores72 commented on android-whitelist.json
> +      "expires": "2022-5-15",
@geroillescas porque estamos agregando una fecha de expire que ya expiro? puede ser que en vez de 2022 sea 2023?

2022-10-11 12:58 UTC, eduflores72 commented on android-whitelist.json
> +      "expires": "2022-5-15",
@geroillescas porque estamos agregando una fecha de expire que ya expiro? puede ser que en vez de 2022 sea 2023?

2022-10-11 17:56 UTC, lcarboneti requested changes
corregir fecha de expiracion

2022-10-13 13:19 UTC, lcarboneti approved these changes

2022-10-13 13:21 UTC, merged