Se modifica fecha de expiracion de libs de MODS
mercadolibre/mobile-dependencies_whitelist pull request #1509
Opened 2022-10-12 13:52 UTC by frarenas

# Descripción
    Se modifica fecha de expiracion de libs de MODS v5
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-10-12 14:29 UTC, gussrivero approved these changes

2022-10-12 17:14 UTC, frarenas commented
@lcarboneti entiendo que mañana migramos sí o sí a la version 6 (podes confirmar @gussrivero)
Mientras necesitamos que el CI pueda terminar para completar algunos prs.

2022-10-13 13:09 UTC, gussrivero commented
@frarenas buenas, hoy es el deadline pero en este caso que el PR llego sobre la fecha podemos dejar una semana de expire para no generar fricciones con algun equipo que la consuma

2022-10-13 16:55 UTC, lcarboneti commented on android-whitelist.json
> +      "expires": "2022-10-13",
@frarenas  Como menciono gus .. dejemos el Expired por unos dias mas para evitar fricciones.. una semana o 2 mas por fa

2022-10-13 16:55 UTC, lcarboneti requested changes
Nueva solicitud

2022-11-22 13:33 UTC, eduflores72 commented
@frarenas este PR en que status quedo ? se puede cerrar ?

2022-11-22 14:39 UTC, frarenas commented
@eduflores72 lo cierro. Ya están productivas las versiones que se deberían usar.

2022-11-22 14:39 UTC, closed without merging