- Bump Dami Ui lib to 2.0.0
mercadolibre/mobile-dependencies_whitelist pull request #1609
Opened 2022-12-06 19:25 UTC by ezecaamanomeli

# Descripción
   - Se actualiza dami ui components lib a versión 2.0.0
# Ticket ID
- - [#7558061]()
    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-12-07 18:49 UTC, lcarboneti commented on android-whitelist.json
> +      "name": "base_testapp",
porque agregamos la base_testapp?

2022-12-07 18:50 UTC, lcarboneti requested changes
algunas dudas

2022-12-07 19:46 UTC, NicoLamberr commented on android-whitelist.json
> +      "name": "base_testapp",
Hola Lucio, base_testapp es un modulo que creamos para darle mayores funcionalidades a la base testapp de meli y acomodarlas a las necesidades funcionales de nuestra lib, por eso la estamos agregando.

2022-12-13 13:46 UTC, NicoLamberr commented
@lcarboneti Buenas, nose si pudiste ver esto

2022-12-13 14:41 UTC, lcarboneti commented on android-whitelist.json
> +      "name": "base_testapp",
Este modulo entiendo que no va a quedar productivo.. no podemos agregarlo dentro de la misma TestApp?

2022-12-13 15:06 UTC, NicoLamberr commented on android-whitelist.json
> +      "name": "base_testapp",
si, es la idea que vaya dentro de la testapp pero para ello no deberia estar en whitelist? o para esos casos no haria falta?

2022-12-14 13:55 UTC, lcarboneti approved these changes

2022-12-14 15:33 UTC, eduflores72 approved these changes

2022-12-14 15:33 UTC, merged