Daisy-whitelist
mercadolibre/mobile-dependencies_whitelist pull request #1626
Opened 2022-12-15 19:53 UTC by cristian-meli

# Descripción
- Daisy-whitelist

# Ticket ID
- #7559569

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2022-12-15 19:58 UTC, gussrivero approved these changes

2022-12-19 13:16 UTC, eduflores72 requested changes

2022-12-19 13:16 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "mercadopago-1\\.\\+|mercadolibre-1\\.\\+"
@cristian-meli que pasa con las libs que venian utilizando esta libs de la forma antigua?

2022-12-19 13:38 UTC, cristian-meli commented on android-whitelist.json
> +      "version": "mercadopago-1\\.\\+|mercadolibre-1\\.\\+"
Hola Edu, esta es una lib nueva aún no es utilizada estamos haciendo pruebas, lamentablemente por mi inexperiencia la entrada de la whitelist la hice mal, así es como debe quedar

2022-12-19 13:59 UTC, eduflores72 commented on android-whitelist.json
> +      "version": "mercadopago-1\\.\\+|mercadolibre-1\\.\\+"
ahhhh perfecto ,muchas gracias por la aclaración, te hacia la consulta porque si era una libs que la estaban utilizando iba comenzar a fallar porque estaban cambiando no solo la versión sino el name de la libs, pero sino la usa nadie le damos para delante.

2022-12-19 13:59 UTC, eduflores72 approved these changes

2022-12-19 13:59 UTC, merged