Loyalty libs updated
mercadolibre/mobile-dependencies_whitelist pull request #1731
Opened 2023-03-09 19:12 UTC by LFeliciML

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-03-09 19:39 UTC, eduflores72 commented on android-whitelist.json
> -      "name": "webview",
@LFeliciML es correcto eliminar name?

2023-03-09 19:40 UTC, eduflores72 commented on android-whitelist.json
> -      "version": "16\\.\\+"
idem comentario anterior

2023-03-09 20:05 UTC, LFeliciML commented on android-whitelist.json
> -      "name": "webview",
Hola Edu, parte de la idea de este update es unificar estas dos versiones ya que son dos packages del mismo repo (No son los unicos) y comparten versión siempre.

2023-03-10 18:02 UTC, eduflores72 approved these changes

2023-03-15 19:47 UTC, tomascorchonML approved these changes

2023-03-16 14:03 UTC, matiasmanzanzani requested changes
El unificar estas libs deberia impactarse en las nuevas dependencias que agregas a la allow list, estas ya que tienen el expire, no se deberian modificar. En caso de que borremos el name va a generar error.

Los cambios que quieran realizar se pueden aplicar en las nuevas dependencias que agreguen a la allow list

2023-03-17 17:36 UTC, LFeliciML commented on android-whitelist.json
> -      "name": "webview",
Como estas Matias? Ahi reverti la eliminacion de esas librerias, les puse un expire y una descripcion con referencia a nuestra wiki explicando el cambio para quien tenga alguna duda, aunque no deberia generar grandes conflictos :D

2023-03-20 14:55 UTC, matiasmanzanzani approved these changes

2023-03-20 17:29 UTC, merged