Add Qualtrics 2.9.1
mercadolibre/mobile-dependencies_whitelist pull request #1739
Opened 2023-03-13 17:21 UTC by aleeevola

# Descripción
   Agregar la libreria Qualtrics
# Ticket ID
- - #7570801

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-03-21 19:35 UTC, abruno- requested changes
blockeado por las dudas

2023-03-30 20:13 UTC, vmagnani approved these changes

2023-03-30 20:14 UTC, henrikemota approved these changes

2023-03-30 20:17 UTC, abruno- approved these changes

2023-03-30 20:17 UTC, merged