comparator dependency added
mercadolibre/mobile-dependencies_whitelist pull request #1751
Opened 2023-03-20 19:34 UTC by tomasmaurente

# Descripción
    Se agrego la dependencia de la librería comparator (ya exisitente en la whitelist) ya que se esta migrando de repositorio
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-03-21 15:02 UTC, gussrivero commented on android-whitelist.json
> +      "group": "com\\.mercadolibre\\.android\\.recommendations_combo",
@tomasmaurente entiendo que se migra de repo esta lib, podemos agregar un expire al repo anterior?

2023-03-21 17:42 UTC, tomasmaurente commented on android-whitelist.json
> +      "group": "com\\.mercadolibre\\.android\\.recommendations_combo",
por ahora queda sin fecha de vencimiento si

2023-03-23 13:59 UTC, tomasmaurente commented on android-whitelist.json
> +      "group": "com\\.mercadolibre\\.android\\.recommendations_combo",
Okey, creo que ponerle de aca a 3 meses va a estar bien, hago el cambio

2023-03-23 14:43 UTC, gussrivero approved these changes

2023-03-23 15:39 UTC, gussrivero requested changes
Hay varios files que no corresponden

2023-03-23 18:36 UTC, gussrivero approved these changes

2023-03-23 19:01 UTC, eduflores72 approved these changes

2023-03-23 19:01 UTC, merged