Bump datadog version
mercadolibre/mobile-dependencies_whitelist pull request #1801
Opened 2023-04-17 21:13 UTC by maoherd

# Descripción
    Actualización de la version de datadog para cambio de la versión de Kotlin 1.8.20
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-04-19 19:14 UTC, eduflores72 requested changes
bloqueamos este PR hasta podamos finalizar el analisis de la libs. a demas tiene relacion con el update de kotlin 1.8 por lo que por el momento no vamos a poder actualizar

2023-08-01 13:23 UTC, maoherd commented
Actualizado PR, ya en appMonitoring v0.12.0 kotlin 1.8.10

2023-08-03 17:40 UTC, maoherd commented
MP -> https://gradle.adminml.com/s/b6x3gz4hjocay
ML -> https://gradle.adminml.com/s/mgabcrmam5xv2

2023-08-03 18:04 UTC, maoherd commented
MP https://gradle.adminml.com/c/t5gesrbdfz3l6/b6x3gz4hjocay/task-inputs
ML https://gradle.adminml.com/c/6epdmymtqul62/mgabcrmam5xv2/task-inputs

2023-08-04 13:03 UTC, maoherd commented
https://gradle.adminml.com/c/juapaz7bulj2y/c7zh4rcprwvfi/build-dependencies

2023-08-04 13:46 UTC, eduflores72 approved these changes

2023-08-04 14:11 UTC, gussrivero approved these changes

2023-08-04 14:28 UTC, merged