Update MPContacts version to 5.0.0 and Realm version to 10.38.0
mercadolibre/mobile-dependencies_whitelist pull request #1863
Opened 2023-05-29 20:50 UTC by nebravo

# Descripción
- Se actualizan los majors de las librerías de MPContacts y Realm
- Se agregan las expiration dates para las versiones anteriores

# Ticket ID
[DATRAN-3826](https://mercadolibre.atlassian.net/browse/DATRAN-3826)

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [X] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-05-30 14:10 UTC, henrikemota commented
Hace un tiempo hablamos de la necesidad real del termos Realm, MPContacts es el único repositorio que tiene Realm

¿Realmente necesitamos? ¿No podemos usar LocalStorage y sacar esta libreria externa?

2023-05-30 22:10 UTC, nebravo commented
Hola @henrikemota 

Si bien todas las soluciones tienen sus ventajas y desventajas, en este caso, no sería adecuado utilizar una solución basada en clave-valor, como el caso del LocalStorage, esto debido a necesitamos un modelado de datos completo y almacenarlos estructuradamente.

Por eso necesitamos un motor de bases de datos que performe muy bien , y nos permita realizar consultas fácil y eficientemente, sobre todo cuando se trata de almacenar y consultar libretas de contactos muy extensas.

2023-06-07 18:24 UTC, caiomatosmeli commented on ios-whitelist.json
> +      "source": "public",
Por que cambiamos el source para "public"?

2023-06-21 15:49 UTC, lcarboneti requested changes
Buenas  @nebravo   , podrias cargarnos  un ticket para la evaluacion de la incorporacion de la libreria externa en esta version por fa.. saludos

2023-06-21 15:58 UTC, nebravo commented
> Buenas @nebravo , podrias cargarnos un ticket para la evaluacion de la incorporacion de la libreria externa en esta version por fa.. saludos

Hola @lcarboneti me indicas en donde cargo el ticket? también para hacer claridad actualmente esa dependencia ya la tenemos solo que está cargada como privada por lo que expliqué en un comentario anterior. Gracias.

2023-07-25 18:12 UTC, caiomatosmeli approved these changes

2023-07-25 18:16 UTC, nebravo commented on ios-whitelist.json
> +      "version": "10.38.0"
@caiomatosmeli actualmente solo la utilizamos nosotros en la librería de MPContacts

2023-07-26 14:44 UTC, merged