Update buyingflow payment version
mercadolibre/mobile-dependencies_whitelist pull request #2074
Opened 2023-09-25 16:07 UTC by PauChittaro

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-09-25 19:52 UTC, eduflores72 requested changes
@pabloferraris bloqueo este PR, hasta que podamos hacer las modificaciones necesarias, en este caso deberiamos agregarle el expire a la version 1.+, y luego agregar la version 2.+. 

Asi como esta ahora se va eliminar la version 1.+ y el dia de la fecha va expirar la version 2.

2023-09-26 13:43 UTC, PauChittaro commented
> @pabloferraris bloqueo este PR, hasta que podamos hacer las modificaciones necesarias, en este caso deberiamos agregarle el expire a la version 1.+, y luego agregar la version 2.+.
> 
> Asi como esta ahora se va eliminar la version 1.+ y el dia de la fecha va expirar la version 2.

Edu ahi actualice con los cambios, como lo ves?

2023-09-26 13:44 UTC, eduflores72 approved these changes

2023-09-26 13:45 UTC, eduflores72 commented
@PauChittaro el cambio ya quedo corregido, podriamos validar que el PR esta fallando el check de jenking, cuando este ok ya podemos mergearlo

2023-09-26 14:20 UTC, merged