Upgrade bitmovin version
mercadolibre/mobile-dependencies_whitelist pull request #2124
Opened 2023-10-18 19:08 UTC by matiasrlucero

# Descripción
se agrega el .+ en el versionado de bitmovin para mejorar la dependencia transitiva
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ x] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ x] Meli Store

2023-10-19 15:49 UTC, gussrivero commented
@matiasrlucero podrias revisar el PR que contiene files .idea

2023-10-19 15:50 UTC, gussrivero commented on android-whitelist.json
> +      "version": "3\\.40\\.0\\.+"
@matiasrlucero no permitimos un versionado dinamico en las libs externas, si requieren el bump por favor agregar la nueva version completa y a la actual dejar una fecha de expiración

2023-10-19 15:59 UTC, eduflores72 requested changes
validar files que se estan agregando de forma incorrecta.
Validar update de libs externa, en caso de necesitar un update, debemos crear el ticket correspondiente y analizar que implica el cambio

2024-01-08 15:43 UTC, eduflores72 commented
@matiasrlucero tenemos algun status sobre este PR? podemos cerrarlo ?

2024-01-08 18:41 UTC, eduflores72 commented
se cierra este PR, se sigue en el siguiente --> https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2272

2024-01-08 18:41 UTC, closed without merging