Added androidx tracing for measure times
mercadolibre/mobile-dependencies_whitelist pull request #2194
Opened 2023-11-27 20:47 UTC by CodeRedNT

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

2023-11-28 20:55 UTC, eduflores72 commented
@CodeRedNT consulta, se creo el ticket en fury para dar soporte para agregar esta libs?

2023-11-28 20:55 UTC, eduflores72 requested changes
bloqueo este PR, hasta tengamos el analisis de lo que amerita agregar esta libs

2023-12-14 12:22 UTC, CodeRedNT commented
Upated with the new Ticket 105930

2023-12-19 21:40 UTC, gussrivero approved these changes

2023-12-20 12:43 UTC, merged