Allow developer settings library 3.+
mercadolibre/mobile-dependencies_whitelist pull request #2424
Opened 2024-03-27 15:59 UTC by JuanDGutierrez

# Descripción
Allow developer configuration library for Selling Framework version 3.+

# Ticket ID
[PSF-2443](https://mercadolibre.atlassian.net/browse/PSF-2443)

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [x] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [x] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [x] No

2024-03-27 19:55 UTC, eduflores72 approved these changes

2024-03-27 19:59 UTC, abruno- requested changes

2024-03-27 19:59 UTC, abruno- commented on android-whitelist.json
> +      "name": "developer_settings",
agreguemos esta lib dentro de granularidad, por el nombre no parece que sea algo que queremos llevar a produccion. Estan seguros de que necesitan q sea usada con **implementation**()?

2024-03-27 20:36 UTC, JuanDGutierrez commented on android-whitelist.json
> +      "name": "developer_settings",
<img width="543" alt="image" src="https://github.com/mercadolibre/mobile-dependencies_whitelist/assets/108093398/42ca86a7-c310-4fef-a545-fe593ad7aa54">

2024-03-27 20:46 UTC, abruno- commented on android-whitelist.json
> +      "name": "developer_settings",
@JuanDGutierrez entonces podes usarla directamente con debugImplementation, y no hace falta sumarla en la allowlist

2024-03-27 20:52 UTC, JuanDGutierrez commented on android-whitelist.json
> +      "name": "developer_settings",
@abruno- 
hice un Pr  en la lib de MPOS  lo agregue como debug Implementation pero el Ci me da este error 

The following dependencies are not allowed:
 (Invalid) com.mercadolibre.android.ispsf:developersettings:3.0.3

2024-04-15 13:36 UTC, abruno- commented on android-whitelist.json
> +      "name": "developer_settings",
@matiasmanzanzani @lcarboneti podemos revisar porque necesitan agregar una lib de debug en la allowlist

2024-04-16 18:01 UTC, lcarboneti commented on android-whitelist.json
> +      "name": "developer_settings",
@JuanDGutierrez  Es posible llevar los cambios de las dependencias debug a la testApp? entiendo son para pruebas y no es necesario tenerlo en el modulo productivo..

2024-04-17 15:58 UTC, lcarboneti approved these changes

2024-04-17 16:54 UTC, gussrivero approved these changes

2024-04-17 17:01 UTC, merged