Remove allows granular in Dev Settings lib
mercadolibre/mobile-dependencies_whitelist pull request #2513
Opened 2024-04-29 16:29 UTC by JuanDGutierrez

# Descripción
Se elimina la granularidad en la libreria de developor_settings
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [x] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [x] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-04-29 20:30 UTC, abruno- commented on android-whitelist.json
>        "name": "developer_settings",
Hola chicos, como estan ?
queremos evitar que "developer_settings" llegue a produccion, por lo que no deberia estar en la allowlist.
Si es absolutamente necesario incluirla en la allowlist, no es una lib que necesitemos en todos lados, por lo que tienen que declarar todos los proyectos donde la van a incluir.

2024-04-29 20:31 UTC, abruno- commented on android-whitelist.json
>        "name": "developer_settings",
entiendo que lo estan siguiendo con @lcarboneti

2024-04-29 21:30 UTC, JuanDGutierrez commented on android-whitelist.json
>        "name": "developer_settings",
es me esta pasando algo muy raro, con la granularidad, no me esta reconociendo la lib en la wallet y me da un crash en tiempo de ejecucion. Yo hice una prueba con esa misma lib pero le cambie el nombre para que no tuviera nada de granularidad y si me reconoce en la wallet esa lib. Esa lib no la estoy llamando directamente en la wallet pero la wallet no me la reconoce.

2024-04-29 21:34 UTC, JuanDGutierrez commented on android-whitelist.json
>        "name": "developer_settings",
@abruno- mejor voy a eliminar la lib y la llamo desde un deepLink por ahora no necesito mas . podrias darme un approve por favor

2024-04-30 14:25 UTC, eduflores72 submitted a review, later dismissed

2024-04-30 15:37 UTC, lcarboneti commented on android-whitelist.json
>        "name": "developer_settings",
@JuanDGutierrez   aunque el flujo se inicie desde  un deepLink no significa que no podamos llegar a produc con la dependencia.. 

Lo que estamos buscando es acotar el scope donde se utiliza esta dependencia/modulo

2024-04-30 16:25 UTC, lcarboneti commented on android-whitelist.json
>        "name": "developer_settings",
El feature de granularidad no es el problema .. 

 he podido resolver en MercadoPago Wallet la depeendencia de DEveloper_setting en forma debug.

2024-04-30 16:26 UTC, lcarboneti commented on android-whitelist.json
>        "name": "developer_settings",
<img width="1364" alt="image" src="https://github.com/mercadolibre/mobile-dependencies_whitelist/assets/46930886/6b001558-9cab-4135-9a50-59a516787e94">

2024-04-30 16:27 UTC, lcarboneti requested changes
revisar la documentacion sobre como manejar las dependencias  para poder resolver este caso :) 

https://sites.google.com/mercadolibre.com/mobile/gu%C3%ADas-y-problemas/gesti%C3%B3n-de-dependencias-con-gradle

2024-05-03 13:10 UTC, closed without merging