Bump interactivemedia to 3.33.0
mercadolibre/mobile-dependencies_whitelist pull request #2583
Opened 2024-05-28 00:18 UTC by nirincon

# Descripción
Se hace upgrade de la lib por que esta deprecada y no tiene soporte par android 14

# Ticket ID
https://web.furycloud.io/help/tickets/121337

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-05-30 13:17 UTC, eduflores72 requested changes
@nirincon antes de realizar el update de esta libs, deberiamos validar los build scan de ML para ver que no actualicemos nada de forma transitiva (creo que actualiza una libs de google play services). de ser asi deberiamos coordinar con la migracion de google play services & firebase. Si podes compartirle el build scan con el compare de master vs master + el update de esta libs para ir revisando

2024-07-17 13:05 UTC, eduflores72 commented on android-whitelist.json
> -      "version": "3\\.29\\.0"
@matiasmanzanzani solamente la utiliza un equipo, lo mejor seria que esta libreria este configurada con el feature de granularity

2024-07-18 12:19 UTC, eduflores72 submitted a review, later dismissed

2024-07-19 14:09 UTC, eduflores72 approved these changes

2024-07-19 17:26 UTC, caiomatosmeli approved these changes

2024-07-19 17:26 UTC, merged