ScannerAndroid changes
mercadolibre/mobile-dependencies_whitelist pull request #2594
Opened 2024-06-03 17:58 UTC by VictorGonzalezMeli

# Descripción
Changes at ml-scanner-android lib:
- v14 added
- Expire dates for previous versions added 

# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [x] SmartPOS
- [x] Alicia: Flex / Logistics
- [ ] WMS
- [x] Meli Store

## Mi dependencia es:
- [x] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-06-03 18:55 UTC, abruno- submitted a review, later dismissed

2024-06-04 13:00 UTC, lcarboneti requested changes
buenas.. porque estamos soportando tantas versiones de la misma dependencia? 

Todas expiran el mismo dia, no deberian haber salido las dependencias viejas?

2024-06-04 17:48 UTC, VictorGonzalezMeli commented
> buenas.. porque estamos soportando tantas versiones de la misma dependencia?
> 
> Todas expiran el mismo dia, no deberian haber salido las dependencias viejas?

Disculpas, ahi lo cambie.

2024-06-04 17:51 UTC, VictorGonzalezMeli commented
> buenas.. porque estamos soportando tantas versiones de la misma dependencia?
> 
> Todas expiran el mismo dia, no deberian haber salido las dependencias viejas?
Perdon, ahi lo simplifique.. Solo vamos a mantener (por un tiempo) las versiones mayores a 12.0.0, ya que integradores fuera de MP utilizan esta version Legacy.

2024-06-07 13:23 UTC, abruno- approved these changes

2024-06-07 17:32 UTC, VictorGonzalezMeli commented
Cierro el PR y abro este [otro](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2608) por estar bloqueado con solicitud de cambios

2024-06-10 12:36 UTC, matiasmanzanzani approved these changes

2024-06-10 14:50 UTC, eduflores72 commented
@VictorGonzalezMeli revisando nuevamente el PR, sigo viendo multiples versiones de scanner. no es recomendable tener tantas versiones de una libs debido a que podemos generar conflictos.

2024-06-10 18:10 UTC, eduflores72 approved these changes

2024-06-10 18:36 UTC, lcarboneti approved these changes

2024-06-10 18:36 UTC, merged