Add fresco animated-gif sub module
mercadolibre/mobile-dependencies_whitelist pull request #2606
Opened 2024-06-07 16:37 UTC by mfzagalh

# Descripción

Add submodule fresco animated-gif

# Ticket ID
- - https://web.furycloud.io/help/tickets/122054?page=1&teams=false

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-06-13 12:55 UTC, matiasmanzanzani approved these changes

2024-06-13 12:59 UTC, gussrivero requested changes
Revisemos pero me parece que existe ya en meli una lib para generar los gif

2024-06-13 13:48 UTC, gussrivero approved these changes

2024-06-13 14:26 UTC, matiasmanzanzani requested changes
Aguardamos el agregado del Expire y la Granularidad para sus repositorios.

2024-06-14 13:44 UTC, matiasmanzanzani commented on android-whitelist.json
> +        "com.mercadolibre.android"
Esta regla no cumple con las necesidades que tenemos. Si agregamos esto estamos habilitando a casi cualquier repositorio, lo que tienen que agregar es el Group ID de las librerias que vayan a utilizar este repo. 

Ejemplo

com.mercadolibre.android.mylib

2024-06-14 14:06 UTC, mfzagalh commented on android-whitelist.json
> +        "com.mercadolibre.android"
Hola Matias, gracias por la aclaración lo valide antes con los chicos del team de home y me comentaron que ese era su package, tambien lo vi en su [gradle.properties](https://github.com/melisource/fury_homes-android/blob/master/gradle.properties#L42), pero entendiendo tu comentario quizá debió quedar así

`com.mercadolibre.android.home`

de todas formas te comento que cerrare este PR ya que decidimos no soportar por ahora Gif en pro de Webp Animado para continuar avanzando

2024-06-14 14:19 UTC, closed without merging