Add maps to granular projects for Firebase migration
mercadolibre/mobile-dependencies_whitelist pull request #2634
Opened 2024-06-14 19:43 UTC by eferrin

# Descripción
    - Se agrega Maps a la lista de projectos con la dependencia de gms maps
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-06-14 21:12 UTC, eduflores72 approved these changes

2024-06-18 12:05 UTC, matiasmanzanzani approved these changes

2024-06-18 18:28 UTC, gussrivero requested changes
Buenas, esta granularidad esta habilitada para los equipos que van a realizar la migración en la primera etapa, luego se liberara para todos los equipos.

2024-06-24 14:20 UTC, eferrin commented
Pero siendo un lib que tienen la dependencia de forma directa deberia tener habilitada la version. Ademas esta agregado commons con lo cual la levaria a todos los equipos

2024-06-26 12:18 UTC, gussrivero commented
@eferrin Entiendo el punto, ahi para que quede claro, la parte de granularidad quedo solo en una primera etapa, luego cuando la migración impacte en las apps se liberara a todas las libs que la utilicen o se agregaran las que faltan. (la migración aun no impacto en las apps por cuestion de un issue y se extendera el deadline de la migración)

2024-06-26 15:14 UTC, eferrin commented
@gussrivero que hago con el ticket de Jira de la migración, lo paso a done aunque no haya podido hacer la migración?
https://mercadolibre.atlassian.net/browse/MLC1-2063?focusedCommentId=14391312

2024-07-01 12:34 UTC, gussrivero commented
@eferrin Buenas Eze, disculpa la demora. El ticket era solo de pruebas, asi que si los podes dejar en DONE, los PRs masivos llegaran luego de que impactemos los cambios en las apps.

2024-08-27 15:27 UTC, abruno- commented
@eferrin queda algo para avanzar este PR ?

2024-08-27 15:52 UTC, gussrivero commented
lo cierro, esto ya esta en master

2024-08-27 15:52 UTC, closed without merging