Fix nav manager 7.+
mercadolibre/mobile-dependencies_whitelist pull request #2701
Opened 2024-07-05 15:59 UTC by jufarangoma

# Descripción
   Se realizan los cambios de este PR https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2684/files 
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-07-05 19:13 UTC, lcarboneti commented on android-whitelist.json
> +        "com.mercadolibre.android"
Esto habilita a todos los proyectos que tengan ese group ID y no solo a la home

2024-07-05 19:13 UTC, lcarboneti requested changes
Debemos cambiar el namespace de la API

2024-07-08 13:56 UTC, jufarangoma commented on android-whitelist.json
> +        "com.mercadolibre.android"
Necesitamos habilitarlo para todo ML entonces por eso el ajuste es necesario, además necesitamos que se bloquee en MP

2024-07-10 15:55 UTC, henrikemota commented on android-whitelist.json
> +        "com.mercadolibre.android"
si esta permitido para todos los meli, no seria necesario agregar la granularidad

2024-07-10 15:55 UTC, henrikemota commented on android-whitelist.json
> +        "com.mercadolibre.android"
no es possible activar solo para ML y bloquear para MP

2024-07-11 16:25 UTC, lcarboneti approved these changes

2024-07-11 16:26 UTC, matiasmanzanzani approved these changes

2024-07-11 16:55 UTC, merged