Added granularities for da components
mercadolibre/mobile-dependencies_whitelist pull request #2726
Opened 2024-07-18 18:59 UTC by martsilva-meli

# Descripción
    Se agregan dependencias granulares usadas en módulos del proyecto da-components-android que son usados en otros proyectos de distintos equipos de Digital Accounts para testing

# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [x] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [x] Si, adjuntar link a nexus.
- [ ] No

2024-07-22 19:28 UTC, caiomatosmeli approved these changes

2024-07-22 19:28 UTC, eduflores72 submitted a review, later dismissed

2024-07-22 20:03 UTC, abruno- requested changes
revisar como hicieron los otros teams

2024-07-22 20:03 UTC, abruno- commented on android-whitelist.json
> +        "com.mercadopago.android.digital_accounts_components"
Hola gente, entiendo que tienen una lib de testing que quieren usar en otros repositorios ?

en ese caso tienen que crear un modulo como han hecho los otros grupos, fijense:
ui_components.test
obile_cryptography.test_utils
security_two_fa.commonstest

estos equipos hacen eso para evitar que las libs de test lleguen a produ
`digital_accounts_components` se incluye en la wallet, y va a llevar las libs de testing a produccion.

2024-07-22 20:54 UTC, martsilva-meli commented on android-whitelist.json
> +        "com.mercadopago.android.digital_accounts_components"
Gracias por el heads up, el repo por suerte estaba en orden, sólo faltaba especificar los módulos de testing en este PR

2024-07-23 16:22 UTC, abruno- approved these changes

2024-07-23 19:50 UTC, merged