[VERTICALES-437] Upgrade version of Modiface dependency
mercadolibre/mobile-dependencies_whitelist pull request #2865
Opened 2024-09-11 19:39 UTC by juaquinones

# Descripción
Se actualiza la librería external de Modiface

# Ticket ID
- #131900

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [x] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [x] Si, adjuntar link a nexus.
- [ ] No

2024-09-23 14:42 UTC, lcarboneti requested changes
Se envio el ticket para el analisis d este cambio?  Nos pasarias el numero si es asi?

2024-09-23 15:26 UTC, juaquinones commented
> Se envio el ticket para el analisis d este cambio? Nos pasarias el numero si es asi?

Hola Lucio, si, generé el ticket en [fury](https://web.furycloud.io/help/tickets/131900) y luego me dijeron que lo hiciera en [shield](https://shield.adminml.com/requests/4416648). Van los dos.

2024-09-23 20:18 UTC, juaquinones commented
Buenas aviso que el ticket quedó aprobado y se hico el upload en nexus, comparto [enlace](https://android.artifacts.furycloud.io/#browse/browse:extra:com%2Fmodiface%2Fmfemakeupkit%2F20.0.1)

2024-09-25 13:07 UTC, juaquinones commented
Buenas @lcarboneti @gussrivero! Cómo andan?
Ya quedó la lib subida a nexus. Precisaría mergear este PR para que no me falle CI en los PRs.

2024-09-25 13:49 UTC, gussrivero approved these changes

2024-09-25 17:43 UTC, Cavigliano approved these changes

2024-09-25 19:31 UTC, juaquinones commented
Hola @lcarboneti, creo que quedó bloqueado el PR por el `change requested`.

2024-09-26 15:02 UTC, lcarboneti requested changes
realizamos la solicitud de esto via ticket y quedo aprobada ?

2024-09-26 15:06 UTC, lcarboneti approved these changes

2024-09-26 15:13 UTC, merged