Update android-whitelist.json
mercadolibre/mobile-dependencies_whitelist pull request #2883
Opened 2024-09-16 14:53 UTC by agustinn1233

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-18 18:47 UTC, mafunes commented on android-whitelist.json
> +        "com.mercadopago.android.point_flow_engine"
I have my concerns about this. 
I understand that there are more teams using Okio, for example the bottom sheet library uses Okio. I don't know if I would restrict it now, since it was always open.

2024-09-18 19:15 UTC, agustinn1233 commented on android-whitelist.json
> +        "com.mercadopago.android.point_flow_engine"
@mafunes this is copied from version 2.8.0, i understand that it was already like this and i decided to leave it to them :D

2024-09-18 19:17 UTC, agustinn1233 commented on android-whitelist.json
> +      "version": "0\\.30\\.1"
we use the same version that is in the apps, but we leave it restricted for canvas only

2024-09-18 19:17 UTC, agustinn1233 commented on android-whitelist.json
> +      "name": "vectordrawable-animated",
we use the same version that is in the apps, but we leave it restricted for canvas only.

2024-09-18 19:17 UTC, agustinn1233 commented on android-whitelist.json
> +      "name": "exifinterface",
new lib only for canvas.

2024-09-18 19:17 UTC, agustinn1233 commented on android-whitelist.json
> +      "name": "androidsvg-aar",
support svg, only use for canvas.

2024-09-18 19:21 UTC, mafunes commented on android-whitelist.json
> +        "com.mercadopago.android.point_flow_engine"
Thanks Agus for the explanation.
I hadn't noticed that 2.8.0 is also had granular configuration. That makes me wonder why bottomsheet library works without being on this list. Is it likely that they use it transitively?

2024-09-18 20:29 UTC, agustinn1233 commented on android-whitelist.json
> +        "com.mercadopago.android.point_flow_engine"
yes correct, since there is nothing that prevents it, that is why it is good now to enable the transitive in false as some deps do and as we do in canvas :D

2024-09-23 14:39 UTC, lcarboneti requested changes
Se enviaron los tickets correspondientes para evaluacion de estas depeendencias? Podrias indicarnos los numeros de tickets por fa? :)

2024-09-23 15:27 UTC, agustinn1233 commented
@lcarboneti No, no se enviaron los tickets, validamos que en las apps estas deps ya existen pero como no se valida whitelist no dan problemas. Estamos utilizando las mismas versiones que en las apps pero precisasmo para canvas.

2024-09-23 15:28 UTC, agustinn1233 commented
@lcarboneti Este cambio lo estamos siguiendo con ale y entendemos que estaria bien, podemos validarlo igual lucho si precisan algo. Nosotros precisamos ingresar ahora con este cambio, finales de esta semana.

2024-09-25 20:19 UTC, abruno- commented on android-whitelist.json
> -      "version": "2\\.6\\.0"
Quedo medio raro el compare, puede ser que estemos eliminando coil-compose?

2024-09-25 20:32 UTC, agustinn1233 commented on android-whitelist.json
> -      "version": "2\\.6\\.0"
Si se estan eliminando esas deps porque ya no se va a tener mas coil, todo lo maneja canvas.

2024-09-25 20:33 UTC, agustinn1233 commented on android-whitelist.json
> -      "version": "2\\.6\\.0"
Los equipos que las estan usando es a modo de poc, aunque no se porque se admitieron en la whitelist.

2024-09-26 13:50 UTC, abruno- approved these changes

2024-09-26 15:01 UTC, lcarboneti approved these changes

2024-09-26 15:01 UTC, merged