added MpGadget
mercadolibre/mobile-dependencies_whitelist pull request #2889
Opened 2024-09-18 14:51 UTC by ddandrade99

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-18 18:06 UTC, henrikemota commented
esta libreria es un frontend o una lib cross?

2024-09-19 13:02 UTC, ddandrade99 commented
> esta libreria es un frontend o una lib cross?

frontend

2024-09-23 18:21 UTC, Cavigliano commented
@ddandrade99 como estas? `MPGadgets` ya tiene fecha para dejar de ser soportada?

2024-09-23 21:24 UTC, ddandrade99 commented
@Cavigliano Sí, tengo expectativas de remover MpGadgets en la próxima release de MercadoPago, 2.350.

2024-09-24 15:44 UTC, ddandrade99 commented
@Cavigliano Se añadió una fecha de expiración para MpGadgets, la fecha 10/10/24 fue pensada para exactamente 2 lanzamientos adelante, para garantizar que expire solo cuando la nueva librería MpGadget ya esté en un 100% de implementación sin ningún fallo.

2024-09-24 20:33 UTC, Cavigliano requested changes

2024-09-24 20:33 UTC, Cavigliano commented on ios-whitelist.json
> +      "expires": "2024-10-10",
el `expire` va antes que el `name`, tambien se puede agregar una descripción para indicar que se reemplaza por la otra lib, ejemplo: 
```
      "description": "This version will be deprecated in favor of...",
      "expires": "2024-10-10",
      "name": "MpGadgets",
```

2024-09-24 21:49 UTC, ddandrade99 commented on ios-whitelist.json
> +      "expires": "2024-10-10",
done

2024-09-25 12:01 UTC, ddandrade99 commented
@Cavigliano estamos bien  para merge?

2024-09-25 13:54 UTC, Cavigliano commented
> @Cavigliano estamos bien para merge?

@ddandrade99 en CircleCI hay un error sobre la fecha seleccionada: 

> [ERROR] name:MpGadgets, group: , expires: 2024-10-10, cannot expire on Wednesday or Thursday

2024-09-25 15:19 UTC, ddandrade99 commented
@Cavigliano listo

2024-09-25 17:56 UTC, ddandrade99 commented
@Cavigliano estamos bien para merge?

2024-09-25 18:32 UTC, closed without merging

2024-09-25 18:34 UTC, Cavigliano commented
Se cierra este PR porque pertenece a una lib frontend que se utiliza en MP. Se generará otro PR para remover `MpGadgets`, la lib que se quiere reemplazar y ya estaba en master.