Add new library FaceValidation
mercadolibre/mobile-dependencies_whitelist pull request #2893
Opened 2024-09-19 16:42 UTC by KevinMunozMendez

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-23 14:36 UTC, lcarboneti requested changes
Agregar una descripcion de para que utilizamos la lib.. 

Quienes son los consumidores de esta dependencia? Agregar granularidad por favor

2024-09-25 13:52 UTC, gussrivero commented
@KevinMunozMendez podriamos completar lo solicitado por favor? asi avanzamos

2024-09-26 15:05 UTC, gussrivero approved these changes

2024-09-26 15:06 UTC, gussrivero commented
@KevinMunozMendez quien consume estas librerias? podriamos agregarlo como granularidad?

2024-09-26 18:13 UTC, KevinMunozMendez commented
rp retest

2024-09-26 18:46 UTC, lcarboneti approved these changes

2024-09-26 18:46 UTC, merged