Change used libs list in arMeasures project
mercadolibre/mobile-dependencies_whitelist pull request #2894
Opened 2024-09-19 17:53 UTC by ricardoSecchin

# Descripción

- Changing libraries used in the WMS Ar Measures project.
  
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-23 14:35 UTC, lcarboneti requested changes
Se realizo la solicitud para el analisis de cada una de estas dependencias? Podrias agregar el ticket de solicitud si es asi??

Podrias por fa explicar para que se utilizan en la descripcion del PR ?

2024-09-25 14:06 UTC, gussrivero commented
@ricardoSecchin tenemos la info solicitada?

2024-09-25 20:54 UTC, ricardoSecchin commented
> @ricardoSecchin tenemos la info solicitada?

Apologies for the delay in getting back to you. I've been reviewing other topics and tomorrow I will fill out the ticket to follow up.

2024-10-15 14:47 UTC, matiasmanzanzani commented
Team ! Como andan??

El ticket que esta en el PR no me esta funcionando, podemos cargar uno valido ?

2024-10-15 15:29 UTC, ricardoSecchin commented
> Team ! Como andan??
> 
> El ticket que esta en el PR no me esta funcionando, podemos cargar uno valido ?

Ticket ajustado!

2024-10-16 16:10 UTC, gussrivero approved these changes

2024-10-18 17:30 UTC, matiasmanzanzani commented
Team, este PR tambien agrega la version de everest canva por favor coordinen para subir la misma version, o al menos un expire

https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2977

2024-10-21 13:34 UTC, SofiaTejerina commented on android-whitelist.json
> +      "group": "com\\.mercadolibre\\.android\\.everest_canvas",
Por que estan agregando canvas?

2024-10-21 20:11 UTC, lcarboneti requested changes
por fa separemos los PR .. Libs externas por un lado y las internas por otro PR 

Se cargaron los tickets de analisis?

2024-10-21 20:12 UTC, lcarboneti commented
dejo el link a los nuevos tickets : 

Add new External Dependency:
:android: https://shield.adminml.com/c/4588
:ios: https://shield.adminml.com/c/4589

Upload artifacts repository
:android: https://shield.adminml.com/c/4181
:ios: https://shield.adminml.com/c/4192

2024-10-29 17:59 UTC, lcarboneti approved these changes

2024-10-29 18:20 UTC, merged