Bump play integrity 1.3.0
mercadolibre/mobile-dependencies_whitelist pull request #2898
Opened 2024-09-20 18:01 UTC by cristiancancelo

# Descripción
    Se requiere realizar el upgrade a la version 1.3.0
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-23 14:31 UTC, lcarboneti commented on android-whitelist.json
> +      "version": "1\\.3\\.0"
tenemos mapeados quienes son los consumers de esta lib?

2024-09-23 14:32 UTC, lcarboneti commented on android-whitelist.json
> +      "version": "1\\.3\\.0"
Podemos llegar a romper algo en este bump?

2024-09-23 14:33 UTC, lcarboneti requested changes
Completar el template del PR para poder continuar. Detallar quienes son los consumers.  

Ya se genero el ticket para la validacion de esta dependencia dentro de nuestro porceso formal de incorporacion de dependencias? Podrian agregar el ticket number?

2024-09-23 20:52 UTC, cristiancancelo commented on android-whitelist.json
> +      "version": "1\\.3\\.0"
Solo nosotros consumimos esta lib
[auth-android-security](https://github.com/melisource/fury_auth-android-security)

2024-09-25 14:09 UTC, gussrivero commented
@cristiancancelo te dejo el ticket que deben completar para esos casos https://shield.adminml.com/requests/create?c=4588

2024-09-25 17:34 UTC, gussrivero commented
Dejo el [ticket](https://shield.adminml.com/requests/4481297) cargado para dar visibilidad

2024-09-25 17:42 UTC, Cavigliano approved these changes

2024-09-26 15:08 UTC, lcarboneti approved these changes

2024-09-26 15:15 UTC, merged