Feature/gamification lib
mercadolibre/mobile-dependencies_whitelist pull request #2900
Opened 2024-09-23 13:08 UTC by dicciannistefano

# Descripción
   Se agrega la lib de [gamification](https://github.com/melisource/fury_engagement-component-android/pull/3)
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-23 14:29 UTC, lcarboneti approved these changes

2024-09-23 14:30 UTC, lcarboneti commented on android-whitelist.json
> +      "version": "0\\.\\+"
por quien seria utilizada esta lib? podemos agregar granularidad por fa?

2024-09-23 14:31 UTC, lcarboneti requested changes
Completar el TEmplate del PR  y revisar el comment por fa

2024-09-24 14:39 UTC, dicciannistefano commented on android-whitelist.json
> +      "version": "0\\.\\+"
La lib se usaria en home por el momento nada mas.

2024-09-25 13:42 UTC, gussrivero commented
@dicciannistefano cuales serian las libs cross que quieren wrappear? (si es que lo entendi correctamente)

2024-09-26 13:36 UTC, gussrivero approved these changes

2024-09-26 15:06 UTC, lcarboneti approved these changes

2024-09-26 15:18 UTC, merged