MLKit17 expire dates removed
mercadolibre/mobile-dependencies_whitelist pull request #2910
Opened 2024-09-24 14:35 UTC by VictorGonzalezMeli

# Descripción
    En Q4 vamos a estar migrando a los actuales consumidores de la version 12 (Legacy, deprecada) a la version 15 de ml_scanner-android ([Migracion](https://docs.google.com/document/d/16Z6LXOAZ_ck-gBJhQM3NdYrnpjs5vKltkKbxy3gzd7E/edit)). Debido a que el integrador Point_smartpos-android es incompatible con MLKit18 (Debido a la ausencia de GooglePlayServices en dispositivos Point) que usa el scanner v15 actual, proveeremos (por medio de Flavors) una v15 con MLKit17 (no dependiente de GooglePlayServices).

# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [X] SmartPOS
- [X] Alicia: Flex / Logistics
- [ ] WMS
- [X] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [X] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-09-24 18:29 UTC, gussrivero requested changes
Bloqueado hasta que terminemos de validar unas cuestiones de implementación

2024-09-25 14:10 UTC, gussrivero approved these changes

2024-09-25 16:02 UTC, abruno- commented on android-whitelist.json
>        "name": "play-services-mlkit-text-recognition",
estamos revisando agregar transitividad

2024-09-25 17:42 UTC, VictorGonzalezMeli commented on android-whitelist.json
>        "name": "play-services-mlkit-text-recognition",
Buenas, seria agregar transitividad oara q el scanner no la lleve como trasnisiva a quien lo implemente? Tanto en este como en la de barcode verdad? Creo estaria bueno, te parece si lo agrego?

2024-09-25 19:29 UTC, VictorGonzalezMeli commented on android-whitelist.json
>        "name": "play-services-mlkit-text-recognition",
```suggestion
      "name": "play-services-mlkit-text-recognition",
        "transitive_configuration": {
          "transitivity": false
        },
```

2024-09-25 19:31 UTC, VictorGonzalezMeli commented on android-whitelist.json
>        "name": "barcode-scanning",
```suggestion
      "name": "barcode-scanning",
       "transitive_configuration": {
         "transitivity": false
       },
```

2024-09-25 19:35 UTC, VictorGonzalezMeli commented on android-whitelist.json
>        "name": "play-services-mlkit-text-recognition",
Listo, ya lo agregue

2024-09-25 19:42 UTC, gussrivero approved these changes

2024-09-26 15:27 UTC, Cavigliano approved these changes

2024-09-27 14:42 UTC, merged