[ISPMPOS-3050] added lib zdfend to whitelist
mercadolibre/mobile-dependencies_whitelist pull request #2955
Opened 2024-10-07 21:16 UTC by santiagoxmedina

# Descripción
    ...
# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ ] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## La categoría de la dependencia es:
- [ ] Frontend
- [ ] Cross

    Para más información sobre la categoria mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#libreria-frontend-x-cross)

## Mi dependencia tienes un uso controlado:
- [ ] Si
- [ ] No
    
    Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#support-for-granular-dependencies)

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

2024-10-08 19:56 UTC, santiagoxmedina commented
rp retest

2024-10-08 19:58 UTC, santiagoxmedina commented
restart

2024-10-15 14:19 UTC, gussrivero approved these changes

2024-10-15 18:51 UTC, matiasmanzanzani commented
Team ! Necesitamos confirmar que esta dependencia va a ser utilizada por Dynamic Features.

2024-10-15 18:54 UTC, matiasmanzanzani requested changes
Necesitamos verificar la implementacion de DF antes de Mergear este PR

2024-10-17 20:49 UTC, matiasmanzanzani approved these changes

2024-10-17 20:51 UTC, merged