[VERTICALES-1381] add rabbit hole versions
mercadolibre/mobile-dependencies_whitelist pull request #3039
Opened 2024-11-11 15:32 UTC by juaquinones

### Descripción

#### Cual es la necesidad de agregar este cambio ? 

> Se agrega el módulo para Android de una librería nueva que se está desarrollando llamada Rabbit Hole.

> **Sobre Rabbit Hole:** Para aumentar la interacción de los usuarios y reducir la dependencia de las búsquedas directas, estamos desarrollando un componente de recomendaciones infinitas. Partiendo del producto que el usuario está visualizando, también aprovecharemos su historial de navegación y comportamiento para mostrar contenido relevante más allá de la categoría actual.
Esto permitirá una experiencia de exploración fluida y personalizada, guiando a los usuarios a descubrir productos que podrían no haber considerado inicialmente, fomentando un ciclo continuo de descubrimiento que los mantenga inmersos dentro del ecosistema del marketplace.

##### Seleccione el tipo de su dependencia.

<table>
    <thead>
        <tr>
            <th><sub>Tipo</sub></th>
            <th><sub>Descripción</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><ul><li> - [x] <sub>Interna</sub></li></ul></td>
            <td><sub>Libreria/modulo desarrollado in-house en base al ecosistema de Meli.</sub></td>
        </tr>
        <tr>
            <td><ul><li> - [ ] <sub>Externa</sub></li></ul></td>
            <td><sub>Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros). Requiere Ticket de Shield.</sub></td>
        </tr>
    </tbody>
</table>

##### ETA

> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 

<details>

<summary>Sección obligatoria para Dependencias Externas</summary>

####  [ℹ️](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) SHIELD Ticket

##### Link de los Tickets

<table>
    <thead>
        <tr>
            <th><sub>Descripción</sub></th>
            <th><sub>Android</sub></th>
            <th><sub>iOS</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><sub>Dependencia Externa con Artefacto en Nexus</sub></td>
            <td><a href="#"><sub>Upload an artifact Android to Repository</sub></a></td>
            <td><a href="#"><sub>Upload an artifact iOS to Repository</sub></a></td>
        </tr>
        <tr>
            <td><sub>Dependencia Externa</sub></td>
            <td><a href="#"><sub>External Dependency Analysis Android</sub></a></td>
            <td><a href="#"><sub>External Dependency Analysis iOS</sub></a></td>
        </tr>
    </tbody>
</table>

##### Agregue el Ticket de Shield.
> [Dependency Shield Ticket]()
 
</details>

### Información

#### Seleccione las Aplicaciones impactadas por esta dependencia. 

<table>
    <thead>
        <tr>
            <th><sub>Mercado Libre</sub></th>
            <th><sub>Mercado Pago</sub></th>
            <th><sub>SmartPOS</sub></th>
            <th><sub>Alicia: Flex / Logistics</sub></th>
            <th><sub>WMS</sub></th>
            <th><sub>Meli Store</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><ul><li> - [x] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
        </tr>
    </tbody>
</table>

#### [ℹ️](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#libreria-frontend-x-cross) Seleccione el tipo de dependencia.  

<table>
    <thead>
        <tr>
            <th><sub>Frontend</sub></th>
            <th><sub>Cross</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><ul><li> - [x] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
        </tr>
    </tbody>
</table>

#### [ℹ️](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#support-for-granular-dependencies) Mi dependencia tienes un uso controlado ?

<table>
    <thead>
        <tr>
            <th><sub>Si</sub></th>
            <th><sub>No</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><ul><li> - [x] </li></ul></td>
            <td><ul><li> - [ ] </li></ul></td>
        </tr>
    </tbody>
</table>

#### Esta dependencia agrega Artefactos (Jar, Arr, Framework, ...) o Dependencias Externos?  
>  En caso de ser Si, agregue el Link de Nexus - [Nexus Link](www.google.com)

<table>
    <thead>
        <tr>
            <th><sub>Si</sub></th>
            <th><sub>No</sub></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><ul><li> - [ ] </li></ul></td>
            <td><ul><li> - [x] </li></ul></td>
        </tr>
    </tbody>
</table>

2024-11-13 13:22 UTC, eduflores72 approved these changes

2024-11-13 15:21 UTC, matiasmanzanzani commented
Team, seamos mas descriptivos en la descripcion del PR, que objetivo tiene esta nueva libreria ?

2024-11-13 15:31 UTC, Cavigliano requested changes
Quitar librería de iOS, pueden usarla directo sobe MLVPP ya que es de test

2024-11-13 15:39 UTC, juaquinones commented
> Team, seamos mas descriptivos en la descripcion del PR, que objetivo tiene esta nueva libreria ?

Ahí se le sumó la descripción. Gracias

2024-11-13 15:43 UTC, juaquinones commented
> @juaquinones por otro lado, dice que es una lib de front, revisen el [README](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/README.md) para mas info. Gracias!

Debería ser cross entonces. Ahí lo ajusto

2024-11-13 17:03 UTC, abruno- commented
@juaquinones consulta es una lib de testing? o es un flujo que estan desarrollando ?

2024-11-13 17:56 UTC, juaquinones commented
> @juaquinones consulta es una lib de testing? o es un flujo que estan desarrollando ?

Hola, es un nuevo flujo que estamos desarrollando. El objetivo de esta versión `0.+` es poder generar las experimentales y simular todo el flujo de releases lo más parecido a la versión final.

2024-11-13 18:02 UTC, abruno- approved these changes

2024-11-14 19:32 UTC, Cavigliano approved these changes

2024-11-14 20:05 UTC, merged