Enable declarative for Advanced Debugger on Android.
mercadolibre/mobile-dependencies_whitelist pull request #3095
Opened 2024-12-05 20:57 UTC by maumar2000

### Descripción
Se agrega Advanced Debugger a la white list de compose en Android.
#### Cual es la necesidad de agregar este cambio?
Poder usar declarativo en Advanced Debugger Android.
> Complete me!

##### Seleccione el tipo de su dependencia.

| Tipo | Descripción |
|-----|--------------|
| <ul><li>- [ ] <sub>Interna</sub></li></ul> | <sub>Libreria/modulo desarrollado in-house en base al ecosistema de Meli.</sub>                    |
| <ul><li>- [ ] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros). Requiere Ticket de Shield.</sub> |

##### ETA

> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo.</li></ul>

<details>
<summary>Sección obligatoria para Dependencias Externas</summary>

#### [ℹ️](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) SHIELD Ticket

##### Link de los Tickets

| Descripción | Android | iOS |
|-------------|---------|-----|
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact Android to Repository</sub></a> | <a href="#"><sub>Upload an artifact iOS to Repository</sub></a> |
| <sub>Dependencia Externa</sub>            | <a href="#"><sub>External Dependency Analysis Android</sub></a>     | <a href="#"><sub>External Dependency Analysis iOS</sub></a>      |

##### Agregue el Ticket de Shield.
> [Dependency Shield Ticket]()

</details>

---

### Información

#### Seleccione las Aplicaciones impactadas por esta dependencia.

| Mercado Libre | Mercado Pago | SmartPOS | Alicia: Flex / Logistics  | WMS | Meli Store |
|---------------|----------------|------------|----------------------|-------|-----------|
| <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul>  | <ul><li>- [ ] </li></ul>  | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul>  |

#### [ℹ️](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#libreria-frontend-x-cross) Seleccione el tipo de dependencia.

| Frontend  | Cross  |
|----------|--------|
| <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |

#### [ℹ️](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#support-for-granular-dependencies) Mi dependencia tiene un uso controlado?

| Si | No |
|---|----|
| <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |

#### Esta dependencia agrega Artefactos (Jar, Arr, Framework, ...) o Dependencias Externas?

> En caso de ser Si, agregue el Link de Nexus - [Nexus Link](www.google.com)

| Si | No |
|---|----|
| <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |

2024-12-06 14:45 UTC, eportasML commented on android-whitelist.json
> +        "com.mercadolibre.android.advanced_debugger",
Esta dependencia no esta permitida para equipos que no son de la app de WMS. Pueden agregarse en la version 1.0.0. 
Revisen si no tienen que agregar las dependencias del BoM de UI y runtime.
Les falta agregar andes components-compose e Integrations-compose. Lo van a necesitar para al menos tener AndesText y el BaseTheme de MP en declarativo

2024-12-06 17:30 UTC, eduflores72 requested changes
blockeo este PR hasta mientras tengamos el ok del team de compose

2024-12-09 20:52 UTC, eportasML approved these changes

2024-12-10 12:22 UTC, eduflores72 approved these changes

2024-12-10 13:57 UTC, gussrivero approved these changes

2024-12-10 13:57 UTC, merged