Added devices_sdk module migrated from security lib
mercadolibre/mobile-dependencies_whitelist pull request #570
Opened 2020-09-18 16:31 UTC by rlopetegui

# Dependencias a proponer
- "com.mercadolibre.android.devices_sdk:devices:1.+"

### ¿Afecta al start-up time de alguna forma?

_Si, tiene un configurator que se ejecuta en el startup de la app pero toda la ejecución es en un thread en background._

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?

_No, no tiene código con NDK_

### Versiones mínimas y máximas del sistema operativo soportadas

_Tiene Min API level 19
_Tiene Max API level 29

### Impacto en el peso de descarga e instalación de la app

_No debería impectar ya que implica deprecar un módulo por otro, pero mientras se espera a que todos los que usan el módulo desde security se migren al de esta lib si. El peso que sumaría es _

## Libs internas (borrar si el PR es para una lib externa)

### Configuración de Bugsnag

- [x] Ya tenemos usuario en Bugsnag, es: **_${device@mercadolibre.com}_**
- [ ] Ya está configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), [iOS](https://github.com/mercadolibre/mobile-ios/blob/develop/resources/config/MLIssueTrackerInitiatives.plist) y **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/moduletracking-configurer/src/main/java/com/mercadolibre/moduletracking_configurer/ModuleTrackingConfigurer.java), [iOS](https://github.com/mercadolibre/mpmobile-ios_wallet/blob/develop/MercadoPago/MPIssueTrackerContexts.plist)

Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas)).

### Contextos
- [x] Ya agregué y/o actualicé el contexto en la [context-whitelist](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/context-whitelist.json)

### Configuración para el SLA de Crashes
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${SPYN}_**
- [ ] Ya está la configuración hecha.
- [x] Necesito que me ayuden a configurarlo.

[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-errores)

## Caso de uso donde necesitamos usar esta lib

_Es una migración del módulo de device que existe en la lib de security. La idea es deprecar el de security y que se pase a utilizar este nuevo módulo en una lib independiente, esto es porque ya no hace sentido tener el módulo de device acoplado a la lib de security porque pertenece a iniciativas diferentes._

### PRs abiertos con este Caso de uso

- [PR de la nueva lib](https://github.com/mercadolibre/fury_devices-sdk-android/pull/2)

### Repositorios afectados
- [Lib de security a la que se le va a deprecar el módulo de device](https://github.com/mercadolibre/fury_auth-android-security)

## En qué apps impacta mi dependencia

- [x] Mercado Libre
- [x] Mercado Pago

2020-09-18 16:37 UTC, jiurchuk approved these changes

2020-09-18 17:17 UTC, samuelsainz approved these changes

2020-09-25 18:21 UTC, jiurchuk approved these changes

2020-09-25 18:22 UTC, jiurchuk approved these changes

2020-09-25 20:09 UTC, abruno- requested changes

2020-09-25 20:09 UTC, abruno- commented on context_whitelist.json
> +            "name": "devices",
existe un equipo de devices ? o esta lib pertenece al equipo de security ?

2020-09-25 20:13 UTC, rlopetegui commented on context_whitelist.json
> +            "name": "devices",
Bruno como va? Si esta lib pertenece al equipo de device, antes estaba como un módulo en una lib del equipo de site security, y para desacoplar responsabilidades la movimos a una lib nuestra.

2020-09-28 13:40 UTC, eferrin approved these changes

2020-09-28 13:41 UTC, abruno- approved these changes

2020-09-28 13:42 UTC, merged