Updated security lib to latest
mercadolibre/mobile-dependencies_whitelist pull request #573
Opened 2020-09-25 19:40 UTC by rlopetegui

# Dependencias a proponer

"com.mercadolibre.android.security:attestation:3.+"

### ¿Afecta al start-up time de alguna forma?

_No hubieron cambios frente a la versión anterior._

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?

_No_

### Versiones mínimas y máximas del sistema operativo soportadas

_Tiene Min API level 19_
_Tiene Max API level 28_

### Impacto en el peso de descarga e instalación de la app

_No cambió el tamaño del módulo_

## Libs internas (borrar si el PR es para una lib externa)

### Configuración de Bugsnag

- [x] Ya tenemos usuario en Bugsnag, es: **_${sitesecurity@mercadolibre.com}_**
- [ ] Ya está configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/moduletracking-configurer/src/main/java/com/mercadolibre/moduletracking_configurer/ModuleTrackingConfigurer.java)

Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas)).

### Contextos
- [x] Ya agregué y/o actualicé el contexto en la [context-whitelist](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/context-whitelist.json)

### Configuración para el SLA de Crashes
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${SITESEC}_**
- [x] Ya está la configuración hecha.
- [ ] Necesito que me ayuden a configurarlo.

[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-errores)

## En qué apps impacta mi dependencia

- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas#h.p_mZ_ODrm21KPv) en la wiki de Mobile

- [x] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2020-09-28 13:30 UTC, jiurchuk commented
Tenemos fecha de expiracion para la v2 ?

2020-09-28 13:42 UTC, eferrin requested changes

2020-09-28 13:42 UTC, eferrin commented on android-whitelist.json
> +      "version": "2\\.\\+|3\\.\\+"
Agregan un expire para la V2

2020-09-28 14:19 UTC, eferrin approved these changes

2020-09-29 19:29 UTC, MathiasNunez approved these changes

2020-09-29 19:29 UTC, RodriP approved these changes

2020-09-29 19:29 UTC, merged