Actualizar versión de la librería  kotlin-stdlib-jdk7 a 1.3.50
mercadolibre/mobile-dependencies_whitelist pull request #606
Opened 2020-11-20 19:33 UTC by jimmyalvarezmeli

# Dependencias a proponer

- "org.jetbrains.kotlin:kotlin-stdlib-jdk7"

### ¿Afecta al start-up time de alguna forma?

_No

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?

_No

### Versiones mínimas y máximas del sistema operativo soportadas

_Tiene Min API level 19_

### Impacto en el peso de descarga e instalación de la app

_ MP 36.2 variant release

### Configuración de Bugsnag

- [ ] Ya tenemos usuario en Bugsnag, es: **_${blah@mercadolibre.com}_**
- [ ] Ya está configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), [iOS](https://github.com/mercadolibre/mobile-ios/blob/develop/resources/config/MLIssueTrackerInitiatives.plist) y **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/moduletracking-configurer/src/main/java/com/mercadolibre/moduletracking_configurer/ModuleTrackingConfigurer.java), [iOS](https://github.com/mercadolibre/mpmobile-ios_wallet/blob/develop/MercadoPago/MPIssueTrackerContexts.plist)

Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas)).

### Contextos
- [ ] Ya agregué y/o actualicé el contexto en la [context-whitelist](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/context-whitelist.json)

### Configuración para el SLA de Crashes
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${SPYN}_**
- [ ] Ya está la configuración hecha.
- [ ] Necesito que me ayuden a configurarlo.

[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-errores)

## Libs externas (borrar si el PR es para una lib interna)

### Empresas conocidas que actualmente usan esta lib

_Si

### Madurez de la lib

_Bastante madura, no es la última versión_

### Mantenimiento externo de la lib (A.K.A. ¿está en desarrollo activo?)

_Sí

### Fecha del último release de la lib

_Nov 2019_

### ¿Se va a wrappear el uso de una libreria externa? ¿Quién va a ser owner de la misma?

_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases de Okhttp. El ownership va a ser el [equipo de X](mailto:x-team@mercadolibre.com)_

### Alternativas disponibles en el mercado: Tradeoffs

_Si, la última versión es 1.4.20:_
- Puede generar menos impacto en los proyectos

## Caso de uso donde necesitamos usar esta lib

_Cualquier app que use kotlin_

### PRs abiertos con este Caso de uso

- [Soporte usuarios V3](https://github.com/mercadolibre/fury_security-options-android/pull/3)

### Repositorios afectados

- [Security Options](https://github.com/mercadolibre/fury_security-options-android)

## En qué apps impacta mi dependencia

- [ ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas#h.p_mZ_ODrm21KPv) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2020-11-25 14:33 UTC, RodriP commented
Hay que ver si esto obliga a los equipos que usan la .30 a subirse a la .70, o habría que ver si queremos dar soporte a ambas o queremos obligar a esa subida. @barriosnahuel

2020-11-25 15:19 UTC, RodriP approved these changes

2020-11-27 16:09 UTC, eferrin requested changes

2020-11-27 16:09 UTC, eferrin commented on android-whitelist.json
> +      "version": "1\\.3\\.30|1\\.3\\.71"
porque cambiamos la version?

2020-11-27 16:13 UTC, jimmyalvarezmeli commented on android-whitelist.json
> +      "version": "1\\.3\\.30|1\\.3\\.71"
Fué un error, la versión no debe ser cambiada.Acabo de hacer un cambio para volver a la versión 40

2020-11-30 19:22 UTC, RodriP approved these changes

2020-11-30 19:34 UTC, jperezgonzal commented on android-whitelist.json
> -      "version": "1\\.3\\.40"
Tiene algún impacto a nivel peso?

2020-11-30 20:03 UTC, jimmyalvarezmeli commented on android-whitelist.json
> -      "version": "1\\.3\\.40"
No señor, _ MP 36.2 variant release fue el valor que quedó en el varian de release

2020-11-30 20:07 UTC, jperezgonzal approved these changes

2020-11-30 20:16 UTC, eferrin approved these changes

2020-11-30 20:17 UTC, merged