Update cho sdk version in Android and iOS
mercadolibre/mobile-dependencies_whitelist pull request #700
Opened 2021-03-25 19:02 UTC by ggerez-meli

# Dependencias a proponer

- Se actualiza la version del sdk de cho en Android.
- Se actualiza la version del sdk de cho en iOS.

2021-03-25 19:08 UTC, RGuarinoML requested changes

2021-03-25 19:08 UTC, RGuarinoML commented on ios-whitelist.json
> +      "version": "^~>\\s?0.[1-9]+.?[1-9]*$"
Con ese cambio soporta 0.[1-9].[1-9]

Lo que necesitamos es -> "version": "^~>\\s?1.[1-9]+.?[1-9]*$"

<img width="243" alt="Screen Shot 2021-03-25 at 16 07 24" src="https://user-images.githubusercontent.com/46828246/112529600-389dd780-8d84-11eb-9859-8438776cf93b.png">

2021-03-26 13:42 UTC, MathiasNunez approved these changes

2021-03-26 15:05 UTC, juanimoli approved these changes

2021-03-26 19:51 UTC, merged