Added "View Binding" dependency: v. 4.1.1
mercadolibre/mobile-dependencies_whitelist pull request #751
Opened 2021-05-18 13:42 UTC by EPENNACHINI

# Dependencias a proponer

- "androidx.databinding:viewbinding:4.1.1"

### ¿Afecta al start-up time de alguna forma?

_No_

### ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?

_No_

### Versiones mínimas y máximas del sistema operativo soportadas

_Min API level 19_

### Impacto en el peso de descarga e instalación de la app

_-_

## En qué apps impacta mi dependencia

- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas#h.p_mZ_ODrm21KPv) en la wiki de Mobile

- [ ] Ya existe, no tengo que agregar ni modificar nada.
- [ ] Hay que agregar lo que pongo a continuación... 👇

2021-05-18 13:45 UTC, juanimoli approved these changes

2021-05-18 15:21 UTC, abruno- requested changes
@EPENNACHINI te agregas el force de la version anterior en las apps ? esto es para evitar que pisemos la version y los teams que no se hayan migrado todavia rompan en produccion ?

2021-05-18 20:55 UTC, EPENNACHINI commented
> @EPENNACHINI te agregas el force de la version anterior en las apps ? esto es para evitar que pisemos la version y los teams que no se hayan migrado todavia rompan en produccion ?

@abruno- , aquí están los dos PRs.:
https://github.com/mercadolibre/mpmobile-android_wallet/pull/13781
https://github.com/mercadolibre/mobile-android/pull/8570

2021-05-18 21:04 UTC, abruno- commented
genial Eric gracias, ya te deje el approve en ambos PRs

2021-05-19 14:47 UTC, abruno- approved these changes

2021-05-19 14:47 UTC, merged