Update of available and expired versions
mercadolibre/mobile-dependencies_whitelist pull request #886
Opened 2021-09-06 16:21 UTC by ssaczkowski-meli

# Todas las dependencias a proponer
- - "com.mercadolibre.android:milestone-tracker:4.0.0"
- - "com.mercadolibre.android:multiimageview:4.0.0"
- - "com.mercadolibre.android:progress-circler:4.0.0"

### ¿Afecta al start-up time de alguna forma?
- [x ] _No, mi Lib no requiere inicialización en el `Application`_

### Repositorios afectados
- [example fend](www.github.com/mercadolibre)

## En qué apps impacta mi dependencia
- [x ] Mercado Libre
- [ ] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Documentación para otros equipos en la sección de libs 
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la wiki de Mobile

- [x] Ya existe, no tengo que agregar ni modificar nada.

2021-09-06 18:17 UTC, abruno- requested changes

2021-09-06 18:17 UTC, abruno- commented on android-whitelist.json
> +      "version": "3\\.\\+|4\\.\\+"
hola @ssaczkowski-meli, nos comentan porque necesitan tener 2 versiones de la lib ? en las apps pueden coexistir 2 versiones ?

2021-09-06 18:39 UTC, ssaczkowski-meli commented on android-whitelist.json
> +      "version": "3\\.\\+|4\\.\\+"
En la versión 4.0.0 incluimos la migración a api 21 y hay libs que todavía no migraron porque no tiene un deadline la migración y tenemos que seguir soportandolas.

2021-09-06 19:11 UTC, ssaczkowski-meli commented on android-whitelist.json
> +      "version": "3\\.\\+|4\\.\\+"
@abruno- acabo de hacer un commit dejando la ultima versión y extendí la fecha de deprecado para el resto 👍

2021-09-06 20:48 UTC, abruno- approved these changes

2021-09-07 12:48 UTC, eduflores72 approved these changes

2021-09-07 12:48 UTC, merged